########################################################
### kafka配置
########################################################
kafka:
  enabled:
    producer: true
    consumer: true
  bootstrap-servers: # 121.4.197.103:9092
  max-block-ms: 6000
  topic:
    basictopic: test
