spring:
  application:
    name: website
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
  resources:
    add-mappings: false
#  datasource:
#    druid:
#      filter:
#        config:
#          enabled: false
#      web-stat-filter:
#        enabled: false
#      stat-view-servlet:
#        enabled: false

server:
  port: 8773
  servlet:
    contextPath: /website
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    basedir: ./logs/tomcat
    accesslog:
      enabled: true
      rotate: true

logging:
  config: ./config/logback.xml
  file:
    path: ./logs/website.log
#  level:
#    com.mpf.website: debug

########################################################
### Actuator 配置
########################################################
# 健康度检查
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
    enabled-by-default: true
  health:
    db.enabled: true
    diskspace.enabled: true
    diskspace.threshold: 10485760
    mongo.enabled: true
    redis.enabled: true
    status.order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

# 代码基本信息
info:
  build:
    artifact: "website"
    name: "blog"
    description: "个人博客"
    version: "1.0.0"
    author: "mpf"