########################################################
### Spring应用配置
########################################################
spring:
  session:
    store-type: redis
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 16
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 16
        min-idle: 0
      timeout: 5000
#    cluster:
#      nodes: 47.99.193.148:7000,47.99.193.148:7001,47.99.193.148:7002,47.99.193.148:7003,47.99.193.148:7004,47.99.193.148:7005
#    sentinel:
#      master: mymaster
#      nodes:

########################################################
### properties setting  动态配置属性
########################################################
properties:
  swagger:
    enabled: true